package com.hanxinbank.p2p.core.common.exception;

public enum Error {
    EMPTY_MOBILE,
    DUPLICATED_MOBILE,
    DUPLICATED_USERNAME,
    INVALID_MOBILE_VERIFY_CODE,
    INVALID_PASSWORD,
    INVALID_USERNAME,
    INVALID_CAPTCHA,
    NOT_ACCEPTED_TERMS_AND_CONDITIONS
}
