CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE TABLE USERS (
  ID                      NUMBER(19),
  USERNAME                VARCHAR2(100),
  PASSWORD                VARCHAR2(100),
  EMAIL                   VARCHAR2(255),
  NAME                    VARCHAR2(100),
  IDENTITY_NUMBER         VARCHAR2(40),
  MOBILE                  VARCHAR2(13),
  IS_MOBILE_AUTHED        BOOLEAN DEFAULT FALSE,
  IS_IDENTITY_AUTHED      BOOLEAN DEFAULT FALSE,
  IS_LOCKED               BOOLEAN DEFAULT FALSE,
  CREATED_AT              TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT              TIMESTAMP DEFAULT SYSDATE,
  VERSION                 NUMBER(19),
  CONSTRAINT PK_USERS_ID PRIMARY KEY (ID),
  CONSTRAINT UK_USERS_USERNAME UNIQUE(USERNAME),
  CONSTRAINT UK_USERS_IDENTITY_NUMBER UNIQUE(IDENTITY_NUMBER),
  CONSTRAINT UK_USERS_MOBILE UNIQUE(MOBILE)
);
COMMENT ON TABLE USERS                            IS '用户表';
COMMENT ON COLUMN USERS.ID			                  IS '用户ID';
COMMENT ON COLUMN USERS.USERNAME	                IS '用户名';
COMMENT ON COLUMN USERS.PASSWORD	                IS '密码';
COMMENT ON COLUMN USERS.EMAIL               	    IS '邮箱';
COMMENT ON COLUMN USERS.NAME	                    IS '姓名';
COMMENT ON COLUMN USERS.IDENTITY_NUMBER	          IS '身份证号码';
COMMENT ON COLUMN USERS.MOBILE                    IS '手机号码';
COMMENT ON COLUMN USERS.IS_MOBILE_AUTHED	        IS '是否已手机认证';
COMMENT ON COLUMN USERS.IS_IDENTITY_AUTHED	      IS '是否已实名认证';
COMMENT ON COLUMN USERS.IS_LOCKED	                IS '是否已锁定';
COMMENT ON COLUMN USERS.VERSION	                  IS '版本号';
COMMENT ON COLUMN USERS.CREATED_AT	              IS '创建时间';
COMMENT ON COLUMN USERS.UPDATED_AT	              IS '更新时间';
