CREATE SEQUENCE SEQ_ADMINS START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE TABLE ADMINS (
  ID                      NUMBER(19),
  USERNAME                VARCHAR2(100),
  PASSWORD                VARCHAR2(100),
  ROLE                    VARCHAR2(30),
  CREATED_AT              TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT              TIMESTAMP DEFAULT SYSDATE,
  VERSION                 NUMBER(19),
  CONSTRAINT PK_ADMINS_ID PRIMARY KEY (ID),
  CONSTRAINT UK_ADMINS_USERNAME UNIQUE(USERNAME)
);
COMMENT ON TABLE ADMINS                            IS '管理员表';
COMMENT ON COLUMN ADMINS.ID			                   IS '管理员ID';
COMMENT ON COLUMN ADMINS.USERNAME	                 IS '管理员用户名';
COMMENT ON COLUMN ADMINS.PASSWORD	                 IS '密码';
COMMENT ON COLUMN ADMINS.ROLE	                     IS '角色';
COMMENT ON COLUMN ADMINS.CREATED_AT	               IS '创建时间';
COMMENT ON COLUMN ADMINS.UPDATED_AT	               IS '更新时间';
COMMENT ON COLUMN ADMINS.VERSION	                 IS '版本号';
