CREATE SEQUENCE SEQ_ACCOUNTS START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE TABLE ACCOUNTS (
  ID                      NUMBER(19),
  USER_ID                 NUMBER(19),
  BALANCE_AMOUNT          NUMBER(19,2),
  FROZEN_AMOUNT           NUMBER(19,2),
  DEAL_PASSWORD           VARCHAR2(100),
  ACCOUNT_TYPE            VARCHAR2(30),
  CREATED_AT              TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT              TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT PK_ACCOUNTS_ID PRIMARY KEY (ID),
  CONSTRAINT FK_ACCOUNTS_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
);
COMMENT ON TABLE ACCOUNTS                            IS '账号表';
COMMENT ON COLUMN ACCOUNTS.ID			                   IS '账号ID';
COMMENT ON COLUMN ACCOUNTS.BALANCE_AMOUNT	           IS '余额';
COMMENT ON COLUMN ACCOUNTS.FROZEN_AMOUNT	           IS '冻结金额';
COMMENT ON COLUMN ACCOUNTS.DEAL_PASSWORD	           IS '交易密码';
COMMENT ON COLUMN ACCOUNTS.ACCOUNT_TYPE	             IS '账号类型';
COMMENT ON COLUMN ACCOUNTS.CREATED_AT	               IS '创建时间';
COMMENT ON COLUMN ACCOUNTS.UPDATED_AT	               IS '更新时间';