CREATE SEQUENCE SEQ_SMS_MESSAGE_TEMPLATE START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE TABLE SMS_MESSAGE_TEMPLATES (
  ID                      NUMBER(19),
  TYPE                    VARCHAR2(50),
  MESSAGE_TEMPLATE        VARCHAR2(4000),
  CREATED_AT              TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT              TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT PK_SMS_MSG_TMPLS_ID PRIMARY KEY (ID)
);
COMMENT ON TABLE SMS_MESSAGE_TEMPLATES                            IS '短信模板表';
COMMENT ON COLUMN SMS_MESSAGE_TEMPLATES.ID			                  IS '模板ID';
COMMENT ON COLUMN SMS_MESSAGE_TEMPLATES.MESSAGE_TEMPLATE	        IS '消息模板';
COMMENT ON COLUMN SMS_MESSAGE_TEMPLATES.CREATED_AT	              IS '创建时间';
COMMENT ON COLUMN SMS_MESSAGE_TEMPLATES.UPDATED_AT	              IS '更新时间';