CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE TABLE USERS (
  ID                    NUMBER(19),
  USERNAME              VARCHAR2(100),
  PASSWORD              VARCHAR2(100),
  EMAIL                 VARCHAR2(255),
  NAME                  VARCHAR2(100),
  GENDER                VARCHAR2(10),
  IDENTITY_TYPE         VARCHAR2(30),
  IDENTITY_NUMBER       VARCHAR2(40),
  BIRTHDAY              DATE ,
  USER_TYPE             VARCHAR2(20),
  MOBILE                VARCHAR2(13),
  AUTHENTICATION_STATUS VARCHAR2(30) DEFAULT 'NOT_AUTHENTICATED',
  CONSTRAINT PK_USERS_ID PRIMARY KEY (ID),
  CONSTRAINT UK_USERS_USERNAME UNIQUE(USERNAME)
);
COMMENT ON TABLE USERS                            IS '用户表';
COMMENT ON COLUMN USERS.ID			                  IS '用户ID';
COMMENT ON COLUMN USERS.USERNAME	                IS '用户名';
COMMENT ON COLUMN USERS.PASSWORD	                IS '密码';
COMMENT ON COLUMN USERS.EMAIL               	    IS '邮箱';
COMMENT ON COLUMN USERS.NAME	                    IS '姓名';
COMMENT ON COLUMN USERS.GENDER	                  IS '性别';
COMMENT ON COLUMN USERS.IDENTITY_TYPE	            IS '证件类型';
COMMENT ON COLUMN USERS.IDENTITY_NUMBER	          IS '证件号码';
COMMENT ON COLUMN USERS.BIRTHDAY	                IS '生日';
COMMENT ON COLUMN USERS.USER_TYPE	                IS '用户类型';
COMMENT ON COLUMN USERS.MOBILE                   IS '手机号码';
COMMENT ON COLUMN USERS.AUTHENTICATION_STATUS	    IS '认证状态';
